# Generated by Django 3.2.18 on 2023-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver_party', models.CharField(max_length=100)),
                ('transaction_completed_time', models.DateTimeField()),
            ],
        ),
    ]
