# Generated by Django 3.2.18 on 2023-06-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0002_b2ctransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_time', models.CharField(max_length=100)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_short_code', models.CharField(max_length=100)),
                ('bill_reference_number', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('org_account_balance', models.CharField(max_length=100)),
                ('third_party_trans_id', models.CharField(max_length=100)),
                ('msisdn', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
